/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: bfcf54987f93199da0710ca064bdb921)
interface __BaseEnv_Env {
	UPDATE_CATALOGS: KVNamespace;
	DEPLOYMENT_ENVIRONMENT: "production" | "staging";
	MAX_CATALOG_BYTES: "262144";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface ProductionEnv {
		UPDATE_CATALOGS: KVNamespace;
		DEPLOYMENT_ENVIRONMENT: "production";
		MAX_CATALOG_BYTES: "262144";
	}
	interface StagingEnv {
		UPDATE_CATALOGS: KVNamespace;
		DEPLOYMENT_ENVIRONMENT: "staging";
		MAX_CATALOG_BYTES: "262144";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DEPLOYMENT_ENVIRONMENT" | "MAX_CATALOG_BYTES">> {}
}
